# fly.toml app configuration file generated for jkanime-vue on 2026-07-18T03:07:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jkanime-vue'
primary_region = 'gru'
console_command = '/code/manage.py shell'

[build]

[env]
  DJANGO_SETTINGS_MODULE = 'jkanime_vue.settings'
  PORT = '8000'
  PYTHONPATH = '/app'

[processes]
  app = 'gunicorn --bind :8000 --workers 2 jkanime_vue.wsgi'
  celery = 'celery -A jkanime_vue worker --loglevel=INFO'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
