# Generated by Django 6.0.7 on 2026-07-10 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('anio', models.IntegerField(default=2024, verbose_name='Año')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('url', models.URLField(help_text='URL de la serie en JKanime', max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número de capítulo')),
                ('ruta_archivo', models.FilePathField(blank=True, help_text='Ruta donde se guardó el archivo físico del capítulo', null=True, path='C:\\Users\\xnega\\Desktop\\anime')),
                ('url_jkanime', models.URLField(help_text='URL del capítulo en JKanime', max_length=500)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='series.serie')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['numero'],
                'unique_together': {('serie', 'numero')},
            },
        ),
    ]
