# Generated by Django 6.0.7 on 2026-07-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='ruta_archivo',
            field=models.FilePathField(blank=True, help_text='Ruta donde se guardo el archivo fisico del capitulo', null=True, path='C:\\Users\\xnega\\Documents\\Proyectos\\jkanime_gestor\\descargas'),
        ),
        migrations.AlterModelTable(
            name='capitulo',
            table='capitulo',
        ),
        migrations.AlterModelTable(
            name='serie',
            table='serie',
        ),
    ]
