# Generated by Django 6.0.7 on 2026-07-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_alter_capitulo_ruta_archivo_alter_capitulo_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='ruta_archivo',
            field=models.FilePathField(blank=True, help_text='Ruta donde se guardo el archivo fisico del capitulo', null=True, path='C:\\Users\\xnega\\Documents\\Proyectos\\jkanime_vue\\jkanime_vue\\descargas'),
        ),
    ]
