# Generated by Django 6.0.7 on 2026-07-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_add_favorito_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de publicación'),
        ),
    ]
