# Generated by Django 6.0.7 on 2026-07-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_add_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='estado',
            field=models.CharField(choices=[('en_emision', 'En emision'), ('concluido', 'Concluido'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20),
        ),
    ]
