# Generated by Django 6.0.7 on 2026-07-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_add_estado_to_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='dia_emision',
            field=models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo'), ('', 'Sin definir')], default='', max_length=15),
        ),
    ]
