# Generated by Django 6.0.7 on 2026-07-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_add_dia_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='ruta_archivo',
            field=models.CharField(blank=True, help_text='Ruta donde se guardo el archivo fisico del capitulo', max_length=500, null=True),
        ),
    ]
